"""Response MOCK"""

API_RESPONSE = {
    "articles": [
        {
            "_id": "f37ce93e40c7bb88e7e3dd6129b62f2b",
            "_score": 13.056851,
            "author": "Wahyu Sibarani",
            "authors": "Wahyu Sibarani",
            "clean_url": "sindonews.com",
            "country": "ID",
            "excerpt": "Tesla berhenti memproduksi Model S dan Model X setir kanan. Informasi ini terungkap dari "
                       "surat resmi Tesla yang diunggah oleh investor Tesla, Sawyer Merrit melalui...",
            "is_opinion": False,
            "language": "id",
            "link": "https://otomotif.sindonews.com/read/1098117/120/tesla-stop-produksi-model-s-dan-x-setir-kanan"
                    "-bagaimana-nasib-indonesia-1684105547",
            "media": "https://pict.sindonews.net/dyn/850/pena/news/2023/05/15/120/1098117/tesla-stop-produksi-model-s"
                     "-dan-x-setir-kanan-bagaimana-nasib-indonesia-uoy.jpg",
            "published_date": "2023-05-14 23:44:57",
            "published_date_precision": "full",
            "rank": 29062,
            "rights": "2023 SINDOnews. All rights reserved.",
            "summary": "Tesla Model X (kiri) dan Tesla Model S (kanan) mulai sekarang hanya tersedia dengan setir "
                       "kiri. Foto: dok Electrec\n \n \nJAKARTA \n - \nTesla\n berhenti memproduksi \nModel S\n dan "
                       "Model X setir kanan. Informasi ini terungkap dari surat resmi Tesla yang diunggah oleh "
                       "investor Tesla, Sawyer Merrit melalui akun Twitter resmi miliknya.Surat itu dikirimkan kepada "
                       "calon konsumen Tesla yang ada di Australia.Dalam surat yang terunggah itu, Tesla mengatakan "
                       "penghentian produksi itu artinya mereka tidak lagi menerima pemesanan unit Tesla Model S dan "
                       "Model X setir kanan.",
            "title": "Tesla Stop Produksi Model S dan X Setir Kanan, Bagaimana Nasib Indonesia?",
            "topic": "news",
            "twitter_account": "@SINDOnews",
        },
        {
            "_id": "44d564ffd77f8c091a53bfea7140dc78",
            "_score": 12.993881,
            "author": "Griffin Davis",
            "authors": "Griffin Davis",
            "clean_url": "techtimes.com",
            "country": "US",
            "excerpt": "If it isn't Musk, then who?",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.techtimes.com/articles/291519/20230514/elon-musk-allegedly-doesnt-run-tesla-then-whos-handling-ev-company.htm",
            "media": "https://1734811051.rsc.cdn77.org/data/images/full/427651/elon-musk-allegedly-doesnt-run-tesla-then-whos-handling-the-ev-company.jpg",
            "published_date": "2023-05-14 17:45:30",
            "published_date_precision": "full",
            "rank": 2599,
            "rights": "All articles are copyrighted by Tech Times",
            "summary": "Griffin Davis \n, Tech Times \n14 May 2023, 01:05 pm\n \n \nElon Musk is allegedly not handling Tesla, as per the latest rumors.\n \n \n(Photo: Justin Sullivan/Getty Images)\n In an aerial view, brand new Tesla cars sit in a parking lot at the Tesla factory on October 19, 2022, in Fremont, California. Electric car maker Tesla will report third-quarter earnings today after the closing bell.\n \n \nThis detail was first reported by \nThe Wall Street Journal\n. Previously, some Tesla investors were furious as they believed that Elon Musk was failing to run the EV manufacturer.",
            "title": "Elon Musk Allegedly Doesn't Run Tesla\u2014So, Who's Handling the EV Company?",
            "topic": "tech",
            "twitter_account": "@TechTimes_News",
        },
        {
            "_id": "d384da19a6219b7999fa55ee5e11194e",
            "_score": 12.980473,
            "author": "Bharat Sharma",
            "authors": "Bharat Sharma",
            "clean_url": "indiatimes.com",
            "country": "IN",
            "excerpt": "While this looks great, the Tesla Bot still needs a series of improvements to match the likes of things robots made by competitors like Boston Dynamics are doing",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.indiatimes.com/technology/news/tesla-bot-takes-its-first-steps-602837.html",
            "media": "https://im.indiatimes.in/content/2023/May/FBImage2_64647ef329070.jpg",
            "published_date": "2023-05-17 06:40:48",
            "published_date_precision": "full",
            "rank": 296,
            "rights": "indiatimes.com",
            "summary": "Tesla Bot still has a long way to go! In a new video, Tesla showed off its Tesla Bots now slowly walking forward without stumbling. \nIn a new video, Tesla's humanoid \nrobots\n may be seen walking together with chassis installed. In addition, they're also seen performing mundane tasks like picking up stuff.\nWhile this looks great, the Tesla Bot still needs a series of improvements to match the likes of things robots made by competitors like Boston Dynamics are doing\n. The Tesla Bot was revealed last year at the company's AI Day event, and since then, the robots have remained a matter of interest.",
            "title": "Tesla Bot Takes Its First Steps: New Video Shows Progress, But Challenges Lie Ahead",
            "topic": "news",
            "twitter_account": None,
        },
        {
            "_id": "674ffcb9fc9be3798fd3faa665efd265",
            "_score": 12.8963585,
            "author": "Finanzen.Net Redaktion",
            "authors": "Finanzen.Net Redaktion",
            "clean_url": "finanzen.net",
            "country": "DE",
            "excerpt": "Wenig Ver\u00e4nderung zeigt am Donnerstagvormittag die Aktie von Tesla. Die Tesla-Aktie zeigte sich zuletzt im Tradegate-Handel kaum unver\u00e4ndert zum Vortag. Es stand ein Kurs von 160,36 EUR an der Tafel. 18.05.2023",
            "is_opinion": False,
            "language": "de",
            "link": "https://www.finanzen.net/nachricht/aktien/tesla-aktie-kursbewegung-18-05-2023-11210110",
            "media": "https://images.finanzen.net/mediacenter/unsortiert/tesla-sergio-monti-photography-660-9028.jpg",
            "published_date": "2023-05-18 09:23:00",
            "published_date_precision": "timezone unknown",
            "rank": 6849,
            "rights": "finanzen.net",
            "summary": "Zum Vortag unver\u00e4ndert notierte die Tesla-Aktie um 09:16 Uhr im Tradegate-Handel bei 160,36 EUR. Die Tesla-Aktie zog in der Spitze bis auf 160,88 EUR an. In der Spitze b\u00fc\u00dfte die Tesla-Aktie bis auf 159,12 EUR ein. Zum Tradegate-Handelsstart notierte das Papier bei 160,50 EUR. Das Handelsvolumen belief sich zuletzt auf 11.534 Tesla-Aktien.\nMit einem Kursgewinn bis auf 316,75 EUR erreichte der Titel am 22.09.2022 ein 52-Wochen-Hoch. Der derzeitige Kurs der Tesla-Aktie liegt somit 49,37 Prozent unter dem 52-Wochen-Hoch.",
            "title": "Tesla Aktie News: S&P 500 Aktie Tesla verzeichnet am Vormittag kaum Ausschl\u00e4ge",
            "topic": "news",
            "twitter_account": None,
        },
        {
            "_id": "fc80458cfd1383d3e05089f7b20fbe49",
            "_score": 12.891502,
            "author": "Markus Sch\u00f6nfeld",
            "authors": "Markus Sch\u00f6nfeld",
            "clean_url": "auto-motor-und-sport.de",
            "country": "DE",
            "excerpt": "Tesla muss in China rund 1,1 Millionen Autos wegen eines Sicherheitsrisikos beim Bremssystem zur\u00fcckrufen. Betroffen sind nahezu alle Modelle, die Tesla jemals in China verkauft hat.",
            "is_opinion": False,
            "language": "de",
            "link": "https://www.auto-motor-und-sport.de/verkehr/rueckruf-tesla-china-probleme-mit-bremsen-rekuperation/",
            "media": "https://imgr1.auto-motor-und-sport.de/Tesla-Model-Y-169FullWidth-9506fb0a-1795613.jpg",
            "published_date": "2023-05-15 11:33:00",
            "published_date_precision": "full",
            "rank": 12275,
            "rights": "auto-motor-und-sport.de",
            "summary": "Tesla\n\n\n\n\n\n\n\n\n1/15\n\nQuicksilver hei\u00dft die neue Farbe f\u00fcr das Tesla Model Y, die Spezialisten in der Gigafactory 4 im brandenburgischen Gr\u00fcnheide entwickelt haben.\n\n\n\n\n\n\n\n\n\n\n\n\nTesla\n\n\n\n\n\n\n\n\n2/15\n\nQuicksilver wollen auch die US-Kunden - aber die Farbe bekommen aktuell nur Interessenten aus China und Europa.\n\n\n\n\n\n\n\n\n\n\n\n\nTesla\n\n\n\n\n\n\n\n\n3/15\n\nQuicksilver erweitert die Tesla-Model-Y-Farbpalette gegen Aufpreis.\n\n\n\n\n\n\n\n\n\n\n\n\nTesla\n\n\n\n\n\n\n\n\n4/15\n\nUS-amerikanische Kunden verzehren sich nach der neuen Tesla-Farbe Quicksilver.",
            "title": "R\u00fcckruf Tesla (China)",
            "topic": "news",
            "twitter_account": "@amsonline",
        },
        {
            "_id": "761b7acf56489faeb176c6f3e3ee3c25",
            "_score": 12.846987,
            "author": "Jake Lerch",
            "authors": "Jake Lerch",
            "clean_url": "nasdaq.com",
            "country": "US",
            "excerpt": "Owning shares of Tesla (NASDAQ: TSLA) can be a roller-coaster ride, and the last 12 months have been no exception. Tesla shares plummeted in 2022, but this year, they've come roaring back to life and are up 39% year to date.",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.nasdaq.com/articles/up-35-in-this-bear-market-is-tesla-a-buy",
            "media": "https://www.nasdaq.com/sites/acquia.prod/files/2019-05/0902-Q19%20Total%20Markets%20photos%20and%20gif_CC8.jpg",
            "published_date": "2023-05-19 21:17:00",
            "published_date_precision": "full",
            "rank": 713,
            "rights": None,
            "summary": "Owning shares of Tesla (NASDAQ: TSLA) can be a roller-coaster ride, and the last 12 months have been no exception. Tesla shares plummeted in 2022, but this year, they've come roaring back to life and are up 39% year to date.\n\nSo, given the current uncertainties in the electric vehicle (EV) market -- and the stock market overall -- is now the right time to load up on shares of the EV giant? Let's take a closer look.\n\nThe bear case: Lower prices, lower margins\n\nThe bear case for Tesla focuses on two declining figures: the price Tesla charges to purchase a vehicle, and its profit on each sale.",
            "title": "Up 35% in This Bear Market, Is Tesla a Buy?",
            "topic": "business",
            "twitter_account": None,
        },
        {
            "_id": "62f02b2ff06b88e3333fa1fca7692ecd",
            "_score": 12.842571,
            "author": "Holger Wittich",
            "authors": "Gregor Hebermehl,Holger Wittich",
            "clean_url": "auto-motor-und-sport.de",
            "country": "DE",
            "excerpt": "Tesla bringt mit dem Model Q und dem Model 2 zwei neue E-Autos auf den Markt. Die Einsteiger-Modelle positionieren sich unter dem Model Y und dem Model 3.",
            "is_opinion": False,
            "language": "de",
            "link": "https://www.auto-motor-und-sport.de/verkehr/tesla-model-q-und-model-2/",
            "media": "https://imgr1.auto-motor-und-sport.de/Tesla-Model-Q-169FullWidth-479b75ab-2001912.jpg",
            "published_date": "2023-05-17 11:04:00",
            "published_date_precision": "full",
            "rank": 12275,
            "rights": "auto-motor-und-sport.de",
            "summary": 'Budget Direct\n\n\n\n\n\n\n\n\n1/38\n\nSuperbike von Tesla - nat\u00fcrlich im Kanten-Look mit schmalen Scheinwerfern. \n\n\n\n\n\n\n\n\n\n\n\n\nBudget Direct\n\n\n\n\n\n\n\n\n2/38\n\nTesla "Hot Hatch": Damit k\u00f6nnte Tesla die Konkurrenz aus Mercedes-AMG 45, BMW M 135i oder Renault Megane RS, Ford Focus ST und Honda Civic Type R aufmischen.\n\n\n\n\n\n\n\n\n\n\n\n\nBudget Direct\n\n\n\n\n\n\n\n\n3/38\n\nTesla Retro-Sportler: Retro-Sportwagen, kantig, filigran, mit viel Chrom und noch l\u00e4ngerer Motorhaube, einen Tesla E-Type inklusive fettem Sound \u2013 der muss dann aus der Konserve kommen.',
            "title": "Tesla Model Q und Model 2",
            "topic": "news",
            "twitter_account": "@amsonline",
        },
        {
            "_id": "0d950518e14eeda7a128f33eeddbea0f",
            "_score": 12.839029,
            "author": "Jake Lerch",
            "authors": "Jake Lerch",
            "clean_url": "fool.com",
            "country": "US",
            "excerpt": "Price reductions are eating away at Tesla's margins. Is it time to buy or sell?",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.fool.com/investing/2023/05/19/up-35-in-this-bear-market-is-tesla-a-buy/",
            "media": "https://g.foolcdn.com/editorial/images/730592/tsla-tesla-growth-stock-market-investment.jpg",
            "published_date": "2023-05-19 21:17:00",
            "published_date_precision": "full",
            "rank": 673,
            "rights": "fool.com",
            "summary": "Owning shares of \nTesla\n \n(\nTSLA\n 1.84%\n)\n can be a roller-coaster ride, and the last 12 months have been no exception. Tesla shares plummeted in 2022, but this year, they've come roaring back to life and are up 39% year to date.\n\n\nSo, given the current uncertainties in the electric vehicle (EV) market -- and the stock market overall -- is now the right time to load up on shares of the EV giant? Let's take a closer look.\n\n\n\n\nImage source: Getty Images.\n\n\n\n\nThe bear case: Lower prices, lower margins\n\n\nThe bear case for Tesla focuses on two declining figures: the price Tesla charges to purchase a vehicle, and its profit on each sale.",
            "title": "Up 35% in This Bear Market, Is Tesla a Buy?",
            "topic": "news",
            "twitter_account": "@themotleyfool",
        },
        {
            "_id": "bb2974bf06782777385cff87446168a1",
            "_score": 12.830076,
            "author": "HT Auto Desk",
            "authors": "HT Auto Desk",
            "clean_url": "hindustantimes.com",
            "country": "IN",
            "excerpt": "Tesla has been trying for nearly 3 years to enter the Indian EV space",
            "is_opinion": False,
            "language": "en",
            "link": "https://auto.hindustantimes.com/web-stories/teslas-tryst-with-india-a-timeline-of-ev-makers-long-road-so-far-41684318870770",
            "media": "https://images.hindustantimes.com/auto/img/2023/05/17/1600x900/Tesla_Elon_Musk_1684319894999_1684319895345.JPG",
            "published_date": "2023-05-17 04:51:10",
            "published_date_precision": "full",
            "rank": 980,
            "rights": "hindustantimes.com",
            "summary": "Tesla has been trying for nearly 3 years to enter the Indian EV space\n \n \n \n \n \n \n \n \n \n \n \n \n \n Tesla has been trying to enter India since 2020. Elon Musk had hinted 2021 as the year of launch\n \n \n \n \n \n \n \n \n \n \n \n \n \n Musk and Tesla team started lobbying in an attempt to reduce high import duty in India through 2021\n \n \n \n \n \n \n \n \n \n \n \n \n \n In January, 2021, Tesla had even set up a team in India to look for showroom spaces\n \n \n \n \n \nCheck product page\n \n \n \n \n \n \n \n \n \n \n \n In July, 2021, T",
            "title": "Tesla's tryst with India: A timeline of EV maker's long road so far",
            "topic": "news",
            "twitter_account": "@HTAutotweets",
        },
        {
            "_id": "b7ce19edc9e2a3b8cc1de115ddca1ae5",
            "_score": 12.8270855,
            "author": "Trevor Jennewine",
            "authors": "Trevor Jennewine",
            "clean_url": "nasdaq.com",
            "country": "US",
            "excerpt": "Cathie Wood is the founder and CEO of Ark Invest, an asset management company focused on disruptive innovation. Wood became a sensation during the early days of the pandemic as her bold investment strategy led to incredible outperformance. The Ark Innovation ETF soared 148% in 20",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.nasdaq.com/articles/cathie-wood-says-tesla-stock-could-soar-1030-by-2027-elon-musk-says-its-the-best-analysis",
            "media": "https://www.nasdaq.com/sites/acquia.prod/files/2019-05/0902-Q19%20Total%20Markets%20photos%20and%20gif_CC8.jpg",
            "published_date": "2023-05-19 15:19:54",
            "published_date_precision": "full",
            "rank": 713,
            "rights": None,
            "summary": "Cathie Wood is the founder and CEO of Ark Invest, an asset management company focused on disruptive innovation. Wood became a sensation during the early days of the pandemic as her bold investment strategy led to incredible outperformance. The Ark Innovation ETF soared 148% in 2020, crushing the 16% return of the broader S&P 500.\n\nAll of those gains have since disappeared, but Wood remains confident in many of the same companies, especially Tesla (NASDAQ: TSLA). Ark recently published a valuation model that prices Tesla at $2,000 per share by 2027, which implies 1,030% upside from its current price.",
            "title": "Cathie Wood Says Tesla Stock Could Soar 1,030% by 2027 -- Elon Musk Says It's the Best Analysis He's Seen",
            "topic": "business",
            "twitter_account": None,
        },
        {
            "_id": "6a0ef8114d47ef33f229faf4e721f6b3",
            "_score": 12.8110695,
            "author": "Trevor Jennewine",
            "authors": "Trevor Jennewine",
            "clean_url": "fool.com",
            "country": "US",
            "excerpt": "Tesla plans to mass produce a robotaxi in 2024, and Ark Invest believes the stock could grow at an explosive pace in the following years.",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.fool.com/investing/2023/05/19/cathie-wood-says-tesla-stock-could-soar-1030-by-27/",
            "media": "https://g.foolcdn.com/editorial/images/733181/0x0-roadster_01.jpg",
            "published_date": "2023-05-19 15:19:54",
            "published_date_precision": "full",
            "rank": 673,
            "rights": "fool.com",
            "summary": "Cathie Wood is the founder and CEO of Ark Invest, an asset management company focused on disruptive innovation. Wood became a sensation during the early days of the pandemic as her bold investment strategy led to incredible outperformance. The \nArk Innovation ETF\n soared 148% in 2020, crushing the 16% return of the broader \nS&P 500\n.\n\n\nAll of those gains have since disappeared, but Wood remains confident in many of the same companies, especially \nTesla \n(\nTSLA\n 2.33%\n)\n. Ark recently published a valuation model that prices Tesla at $2,000 per share by 2027, which implies 1,030% upside from its current price.",
            "title": "Cathie Wood Says Tesla Stock Could Soar 1,030% by 2027 -- Elon Musk Says It's the Best Analysis He's Seen",
            "topic": "news",
            "twitter_account": "@themotleyfool",
        },
        {
            "_id": "3fd0088e02505481bb45b32c7c62eb33",
            "_score": 12.809018,
            "author": "Randall Chase",
            "authors": "Ap Business Writer,RANDALL CHASE",
            "clean_url": "timesunion.com",
            "country": "US",
            "excerpt": "DOVER, Del. (AP) \u2014",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.timesunion.com/business/article/state-supreme-court-overturns-judge-s-ruling-18100960.php",
            "media": "https://s.hdnux.com/photos/01/32/71/25/23827788/3/rawImage.jpg",
            "published_date": "2023-05-15 22:25:25",
            "published_date_precision": "full",
            "rank": 2528,
            "rights": "timesunion.com",
            "summary": "FILE - A Tesla Supercharger is seen at Willow Festival shopping plaza parking lot, Aug. 10, 2022, in Northbrook, Ill. On Monday, May 15, 2023, Delaware's Supreme Court overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers.\nNam Y. Huh/AP\nDelaware's Supreme Court on Monday overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers.",
            "title": "State Supreme Court overturns judge's ruling prohibiting Tesla dealership in Delaware",
            "topic": "news",
            "twitter_account": "@TimesUnion",
        },
        {
            "_id": "a92fa0166410d5ac508e55ad5454a6ad",
            "_score": 12.808512,
            "author": "Vanya Gautam",
            "authors": "Vanya Gautam",
            "clean_url": "indiatimes.com",
            "country": "IN",
            "excerpt": "Just a handful of days after announcing new Twitter CEO, Elon Musk is back to focusing on Tesla. The Tesla CEO has said that the company can make no new hires unless he personally approves them.",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.indiatimes.com/worth/news/elon-musk-says-tesla-will-not-hire-without-his-personal-approval-602746.html",
            "media": "https://im.indiatimes.in/content/2023/May/With-Focus-Back-On-Tesla-Elon-Musk-Says-No-One-Will-Be-Hired-Without-His-Personal-Approval_64635b395a086.jpg",
            "published_date": "2023-05-16 10:22:56",
            "published_date_precision": "full",
            "rank": 296,
            "rights": "indiatimes.com",
            "summary": 'Just a handful of days after announcing new Twitter CEO, \nElon Musk\n is back to focusing on Tesla\n.\u00a0"Bringing on \nLinda \n(as new Twitter CEO) allows me to devote more time to Tesla, which is exactly what I will be doing," Musk mentioned last week.\nAnd now, the Tesla CEO has said that the EV company can make no new hiring unless he personally approves them, including contractors, according to a copy of the email seen by \nReuters\n.\n\n \nafp\nAccording to the email, Musk told executives to send him a list of hiring requests on a weekly basis, while also cautioning them to "think carefully" before submitting such requests.',
            "title": "With Focus Back On Tesla, Elon Musk Says No One Will Be Hired Without His Personal Approval",
            "topic": "news",
            "twitter_account": None,
        },
        {
            "_id": "66848548f0eaa2efc18f6a2c9170b757",
            "_score": 12.791908,
            "author": "Elyse Betters Picaro",
            "authors": "Adrian Willings,Chris Hall,Elyse Betters Picaro,Luke Baker,Max Freeman-Mills,Oliver Haslam,Rik Henderson",
            "clean_url": "pocket-lint.com",
            "country": "GB",
            "excerpt": "Welcome to Pocket-lint, for the latest electronic product reviews, including news on gadgets, digital cameras, home cinema, audio, cars and mobile phone.",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.pocket-lint.com/tesla/",
            "media": "https://static1.pocketlintimages.com/wordpress/wp-content/uploads/social/pl-og-img.png",
            "published_date": "2023-05-20 12:15:00",
            "published_date_precision": "timezone unknown",
            "rank": 3394,
            "rights": "pocket-lint.com",
            "summary": "Here's everything you need to know about Tesla Motors, from the Roadster through to the Model Y and Cybertruck.\n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \nTesla has slashed the prices of some of its cars around the world as deliveries miss projections.\n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n\u00a0The new features are included in Tesla's Holiday Update, which the company said is rolling out now.\n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \nTesla is now allowing everyone in North America to sign up for its Full Self-Driving beta, no matter what their safety score might be.",
            "title": "Tesla",
            "topic": "news",
            "twitter_account": "@Pocketlint",
        },
        {
            "_id": "155f8a2a36c73e98e43f10c7b0fb09ba",
            "_score": 12.776711,
            "author": "Clark Schultz",
            "authors": "Clark Schultz,SA News Editor",
            "clean_url": "seekingalpha.com",
            "country": "US",
            "excerpt": "Tesla (TSLA) continued to drift slowly higher on Thursday with investors still reacting to some of the developments flowing out of the annual meeting earlier in the week. Read more.",
            "is_opinion": False,
            "language": "en",
            "link": "https://seekingalpha.com/news/3973151-tesla-bulls-are-recharged-after-annual-meeting",
            "media": "https://static.seekingalpha.com/cdn/s3/uploads/getty_images/1140451212/image_1140451212.jpg?io=getty-c-w750",
            "published_date": "2023-05-18 17:11:50",
            "published_date_precision": "full",
            "rank": 892,
            "rights": "seekingalpha.com",
            "summary": "Spencer Platt\n \nTesla (\nNASDAQ:\nTSLA\n) continued to drift slowly higher on Thursday with investors still reacting to some of the developments flowing out of the annual meeting earlier in the week.\n \nElon Musk warned during the meeting that Tesla (\nTSLA\n) is not\n immune from what could be a tough period for the economy and additional pressure on consumer discretionary spending could be seen. However, he also surprised with a tease that Tesla (\nTSLA\n) will try out media advertising and highlighted that new models are in the works.",
            "title": "Tesla bulls are recharged after annual meeting",
            "topic": "news",
            "twitter_account": "@SeekingAlpha",
        },
        {
            "_id": "27dc5f37bcd4d62a235bc2268f350809",
            "_score": 12.776057,
            "author": "Livemint",
            "authors": "Livemint",
            "clean_url": "livemint.com",
            "country": "IN",
            "excerpt": "The settlement in 2018 was done citing tweets by Elon Musk on micro blogging platform Twitter, which he now owns, wherein Musk had mentioned that he had secured funding to take Tesla private, which in\u2026",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.livemint.com/news/world/elon-musks-appeal-to-end-2018-twitter-sitter-deal-for-tesla-posts-rejected-by-us-court-11684231342026.html",
            "media": "https://www.livemint.com/lm-img/img/2023/05/16/600x338/PEOPLE-JEFFREY-EPSTEIN-MORGAN-ELON-MUSK-2_1684231423265_1684231639653.JPG",
            "published_date": "2023-05-16 10:57:40",
            "published_date_precision": "full",
            "rank": 1404,
            "rights": "livemint.com",
            "summary": "A US Federal Appeals Court has rejected Tesla Chief Elon Musk's plea to get out of the settlement he had made in 2018 with US Securities and Exchange Commission, which required him to get all tweets regarding Tesla pre-approved by a lawyer.\u00a0\n \n \n The settlement in 2018 was done citing tweets by \nElon Musk\n on micro blogging platform Twitter, which he now owns, wherein Musk had mentioned that he had secured funding to take Tesla private, which in turn caused the electric vehicle maker's share price to jump.",
            "title": "Elon Musk's appeal to end \u2018Twitter sitter' deal for Tesla posts rejected by US court",
            "topic": "news",
            "twitter_account": "@mint",
        },
        {
            "_id": "aac8382f4d75ca2ecb795fdf6b5a0e66",
            "_score": 12.774721,
            "author": "Steven Loveday",
            "authors": "Steven Loveday",
            "clean_url": "msn.com",
            "country": "US",
            "excerpt": "Several states still make it illegal for Tesla to sell its cars without using a franchised dealership model, but Tesla is winning.",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.msn.com/en-xl/news/other/state-supreme-court-reverses-ban-on-tesla-store-sales/ar-AA1bgvqU",
            "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AAYZs5Q.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg",
            "published_date": "2023-05-16 16:45:00",
            "published_date_precision": "timezone unknown",
            "rank": 100,
            "rights": "msn.com",
            "summary": '\u00a9 InsideEVs\n Tesla store\nThe Delaware Supreme Court officially reversed an earlier decision that made it illegal for Tesla to have a store in the state to sell its electric cars. Now, Tesla can own its own "dealership" and move forward with its direct-to-consumer sales strategy in the state.\nTesla still can\'t sell its EVs in several US states since it relies on direct sales. Essentially, lawmakers in the states that oppose Tesla sales believe the company would be breaking the law by owning its own "dealerships" and selling its own cars without a "middleman.',
            "title": "State Supreme Court Reverses Ban On Tesla Store Sales",
            "topic": "news",
            "twitter_account": None,
        },
        {
            "_id": "cda6b7b74403d83f85d83d6f4e132ccc",
            "_score": 12.770176,
            "author": "Finanzen.Net Redaktion",
            "authors": "Finanzen.Net Redaktion",
            "clean_url": "finanzen.net",
            "country": "DE",
            "excerpt": "Die Aktie von Tesla hat am Dienstagvormittag nur geringe Kursbewegungen zu verzeichnen. Kaum Bewegung lie\u00df sich zuletzt bei der Tesla-Aktie ausmachen. Das Papier notierte via Tradegate bei 153,00 EUR. 16.05.2023",
            "is_opinion": False,
            "language": None,
            "link": "https://www.finanzen.net/nachricht/aktien/tesla-aktie-kursbewegung-16-05-2023-11210110",
            "media": "https://images.finanzen.net/mediacenter/unsortiert/tesla_johannes_eisele_afp_getty4580.jpg",
            "published_date": "2023-05-16 09:23:00",
            "published_date_precision": "timezone unknown",
            "rank": 6849,
            "rights": "finanzen.net",
            "summary": "Die Tesla-Aktie bewegte sich um 09:20 Uhr kaum. Das Papier stand via Tradegate bei 153,00 EUR. Den h\u00f6chsten Stand des Tages erreichte die Tesla-Aktie bisher bei 153,00 EUR. Die Tesla-Aktie gab in der Spitze bis auf 152,02 EUR nach. Zum Start in den Handelstag hatte das Papier einen Wert von 152,54 EUR. Das Handelsvolumen belief sich zuletzt auf 13.744 Tesla-Aktien.\nDer Anteilsschein kletterte am 22.09.2022 auf bis zu 316,75 EUR und markierte damit ein 52-Wochen-Hoch. Damit befindet sich das 52-Wochen-Hoch 107,03 Prozent \u00fcber dem aktuellen Kurs der Tesla-Aktie.",
            "title": "Tesla Aktie News: S&P 500 Aktie Tesla am Vormittag mit stabiler Tendenz",
            "topic": "news",
            "twitter_account": None,
        },
        {
            "_id": "cbd9a71972fa83d05189fc1dc576b3ab",
            "_score": 12.762643,
            "author": "Pm Est",
            "authors": "Ap Business Writer,Associated Press,Nam Y. Huh,Pm Est",
            "clean_url": "ap.org",
            "country": "GB",
            "excerpt": None,
            "is_opinion": False,
            "language": "en",
            "link": "http://hosted.ap.org/journalrecord/article/ef22d03da07b4c291d8ce76ba9a3cfef/state-supreme-court-overturns-judges-ruling-prohibiting",
            "media": "https://mapi.associatedpress.com/v1/items/825372bfe77843e49a5d2d321b1ea598/preview/preview.jpg?s=680x",
            "published_date": "2023-05-15 22:34:01",
            "published_date_precision": "full",
            "rank": 891,
            "rights": "Copyright 2015 The Associated Press",
            "summary": "FILE - A Tesla Supercharger is seen at Willow Festival shopping plaza parking lot, Aug. 10, 2022, in Northbrook, Ill. On Monday, May 15, 2023, Delaware's Supreme Court overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers. (AP Photo/Nam Y. Huh, File) \n \n \n \n \nDOVER, Del. (AP) \u2014 \n \nDelaware's Supreme Court on Monday overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers.",
            "title": "State Supreme Court overturns judge's ruling prohibiting Tesla dealership in Delaware",
            "topic": "business",
            "twitter_account": None,
        },
        {
            "_id": "ad04b6ccc8290ad2b5c84fc75471bd44",
            "_score": 12.762591,
            "author": "Ajede Udam",
            "authors": "Ajede Udam",
            "clean_url": "celebritiesdeaths.com",
            "country": "unknown",
            "excerpt": "Introduction Tesla is a company that is famous for its electric cars and renewable energy solutions. However, the company's operations extend beyond just electric cars. Tesla also produces batteries\u2026",
            "is_opinion": False,
            "language": "en",
            "link": "https://celebritiesdeaths.com/tesla-lithium-refinery-corpus-christi-teslas-lithium-refinery-in-corpus-christi-has-been-revamped/",
            "media": "https://i0.wp.com/celebritiesdeaths.com/wp-content/uploads/2023/05/tesla-lithium-refinery-corpus-christi-teslas-lithium-refinery-in-corpus-christi-has-been-revamped_26101.jpg",
            "published_date": "2023-05-15 01:30:08",
            "published_date_precision": "full",
            "rank": 22589,
            "rights": "celebritiesdeaths.com",
            "summary": "Introduction\n\n\nTesla is a company that is famous for its electric cars and renewable energy solutions. However, the company's operations extend beyond just electric cars. Tesla also produces batteries for its cars and energy storage systems. The company is also working on developing a lithium refinery in Corpus Christi, Texas. This refinery will enable Tesla to produce its own lithium for its batteries, which will reduce the company's reliance on third-party suppliers. In this article, we will explore the Tesla Lithium Refinery Corpus Christi in more detail and discuss its potential impact.",
            "title": "Tesla Lithium Refinery Corpus Christi : Tesla's Lithium Refinery in Corpus Christi has been revamped.",
            "topic": "news",
            "twitter_account": None,
        },
        {
            "_id": "51e8c78ff7d55ad6f1551970b9fb0c2a",
            "_score": 12.761493,
            "author": "Jobpie Sugiharto",
            "authors": "Dicky Kurniawan,Jobpie Sugiharto",
            "clean_url": "tempo.co",
            "country": "ID",
            "excerpt": "Tesla memiliki pasar mobil listrik setir kanan, antara lain Inggris, Jepang, dan Hongkong. Tidak ada lagi Tesla Model S dan Model X setir kanan.",
            "is_opinion": False,
            "language": "id",
            "link": "https://otomotif.tempo.co/read/1725946/tesla-model-s-dan-model-x-setir-kanan-disuntik-mati",
            "media": "https://statik.tempo.co/data/2023/02/28/id_1184915/1184915_720.jpg",
            "published_date": "2023-05-15 08:00:00",
            "published_date_precision": "full",
            "rank": 9966,
            "rights": "tempo.co",
            "summary": "TEMPO.CO\n, \nJakarta\n - \nTesla\n Inc. mengonfirmasi tidak lagi menawarkan mobil listrik varian setir kanan untuk Tesla Model S dan Model X. \nKedua model tersebut sekarang masih tersedia dalam varian setir kiri.\nMelansir laman \nAutoblog\n hari ini, Senin, 15 Mei 2023, alasan Tesla tidak memproduksi lagi varian \nsetir kanan\n adalah menjaga biaya produksi tetap terkendali dengan memangkas roses produksi. \nPembuatan \nmobil listrik\n Tesla setir kanan memiliki kerumitan mekanis dan logistik yang ditambahkan untuk konversi.",
            "title": "Tesla Model S dan Model X Setir Kanan Disuntik Mati",
            "topic": "news",
            "twitter_account": None,
        },
        {
            "_id": "0273b393d47955c331069eaa24630181",
            "_score": 12.758339,
            "author": "",
            "authors": "",
            "clean_url": "breitbart.com",
            "country": "US",
            "excerpt": "Delaware's Supreme Court has overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.breitbart.com/news/state-supreme-court-overturns-judges-ruling-prohibiting-tesla-dealership-in-delaware/",
            "media": "https://media.breitbart.com/media/2023/05/wi/ap/tesla-delaware-tesla-supercharger-is-at-willow-festival-shopping-plaza-parking-lot-aug-10-2022-northbrook-640x335.jpg",
            "published_date": "2023-05-15 15:31:43",
            "published_date_precision": "full",
            "rank": 1462,
            "rights": "breitbart.com",
            "summary": "Delaware's Supreme Court has overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers\n\n\nState Supreme Court overturns judge's ruling prohibiting Tesla dealership in DelawareBy RANDALL CHASEAP Business WriterThe Associated PressDOVER, Del.\n\n\n\n\n\n\nDOVER, Del. (AP) \u2014\n\n\nDelaware's Supreme Court on Monday overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers.",
            "title": "State Supreme Court overturns judge's ruling prohibiting Tesla dealership in Delaware",
            "topic": "news",
            "twitter_account": "@BreitbartNews",
        },
        {
            "_id": "3869f430b353c5ce2f9118f3ff6b0c81",
            "_score": 12.755473,
            "author": "World Today News",
            "authors": "World Today News",
            "clean_url": "world-today-news.com",
            "country": "US",
            "excerpt": "Tesla is launching two new electric cars, the Model Q and the Model 2. The entry-level models are positioned below the Model Y and the Model 3. Holger Wittich, Gregor Hebermehl 17.05.2023 At Tesla's\u2026",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.world-today-news.com/tesla-announces-launch-of-model-q-and-model-2-as-entry-level-electric-cars/",
            "media": "https://imgr1.auto-motor-und-sport.de/Tesla-Model-Q-169FullWidth-479b75ab-2001912.jpg",
            "published_date": "2023-05-17 14:15:51",
            "published_date_precision": "full",
            "rank": 38139,
            "rights": "world-today-news.com",
            "summary": "Skip to content\n \nModel Q as small Model Y\n\n\nHe thus confirmed rumors of an all-new, mass-produced small SUV that is to be positioned below the popular Tesla Model Y. This model could trade under the name 'Model Q'.\n \nMusk forecast annual production of more than five million units for the two new products, which he promised will be developed and produced using techniques that 'far exceed anything else in the industry.' Both get a new 48-volt architecture and the latest version of the 'power unit', which probably does without rare earths, contains 25 percent less silicon carbide and requires 50 percent less space than the current motors.",
            "title": '"Tesla Announces Launch of Model Q and Model 2 as Entry-Level Electric Cars"',
            "topic": "sport",
            "twitter_account": None,
        },
        {
            "_id": "504c535160639d74b2723565efb42956",
            "_score": 12.754266,
            "author": "Delaware News Journal",
            "authors": "Delaware News Journal",
            "clean_url": "yahoo.com",
            "country": "US",
            "excerpt": "Start looking for a supercharger station. Delaware's Supreme Court overturns ruling prohibiting Tesla dealerships in the state.",
            "is_opinion": False,
            "language": "en",
            "link": "https://news.yahoo.com/delawares-tesla-dealership-restrictions-overturned-133539671.html",
            "media": "https://s.yimg.com/ny/api/res/1.2/Z.Tc7oET_7H6KBCdEkkt7g--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/delaware-online-the-news-journal/90960acc8611ff9af9ba780baf3adb77",
            "published_date": "2023-05-18 13:35:39",
            "published_date_precision": "full",
            "rank": 31,
            "rights": "yahoo.com",
            "summary": "DOVER, Del. \u2014 Delaware's Supreme Court on Monday overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers.\nIn a ruling last year, a Superior Court judge determined that Delaware's Motor Vehicle Franchising Practices Act prohibited Tesla, as a manufacturer, from selling its electric cars directly to customers in Delaware.\nThe Supreme Court reversed that decision and sent the case back to Superior Court, noting that the franchise act was enacted to address the disparity in bargaining power that permitted automobile manufacturers to exert economic pressure over their franchises.",
            "title": "Delaware's Tesla dealership restrictions overturned by State Supreme Court",
            "topic": "news",
            "twitter_account": "@YahooNews",
        },
        {
            "_id": "fdbf63ca18543d895e688bfd45232f29",
            "_score": 12.750697,
            "author": "Abc News",
            "authors": "ABC News,RANDALL CHASE",
            "clean_url": "go.com",
            "country": "US",
            "excerpt": "Delaware's Supreme Court has overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers",
            "is_opinion": False,
            "language": "en",
            "link": "https://abcnews.go.com/Business/wireStory/state-supreme-court-overturns-judges-ruling-prohibiting-tesla-99343800",
            "media": "https://s.abcnews.com/images/Business/wirestory_ef22d03da07b4c291d8ce76ba9a3cfef_16x9_992.jpg",
            "published_date": "2023-05-15 22:25:23",
            "published_date_precision": "full",
            "rank": 120,
            "rights": "go.com",
            "summary": "Delaware's Supreme Court has overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers\nFILE - A Tesla Supercharger is seen at Willow Festival shopping plaza parking lot, Aug. 10, 2022, in Northbrook, Ill. On Monday, May 15, 2023, Delaware's Supreme Court overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers.",
            "title": "State Supreme Court overturns judge's ruling prohibiting Tesla dealership in Delaware",
            "topic": "news",
            "twitter_account": "ABC News",
        },
        {
            "_id": "d0c0530c545174b39492b480b5fb9969",
            "_score": 12.747836,
            "author": "\u0414\u0430\u0440\u044c\u044f \u0413\u0443\u0431\u0438\u043d\u0430",
            "authors": "\u0414\u0430\u0440\u044c\u044f \u0413\u0443\u0431\u0438\u043d\u0430,\u041d\u0438\u043a\u043e\u043b\u0430\u0439 \u0413\u043e\u043b\u043e\u0432\u0438\u043d,\u0420\u0435\u0434\u0430\u043a\u0446\u0438\u044f Naked Science",
            "clean_url": "naked-science.ru",
            "country": "RU",
            "excerpt": "\u041a\u043e\u043c\u043f\u0430\u043d\u0438\u044f Tesla \u043f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u0438\u043b\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u043d\u0443\u044e \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044e \u043e \u0441\u0432\u043e\u0435\u0439 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0435 \u0440\u043e\u0431\u043e\u0442\u043e\u0432-\u0433\u0443\u043c\u0430\u043d\u043e\u0438\u0434\u043e\u0432, \u0438\u0437\u0432\u0435\u0441\u0442\u043d\u043e\u0439 \u043a\u0430\u043a Tesla Bot \u0438\u043b\u0438 Optimus. \u041d\u043e\u0432\u044b\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f \u043f\u0440\u043e\u0442\u043e\u0442\u0438\u043f\u043e\u0432 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u044f\u0442 \u0432\u043f\u0435\u0447\u0430\u0442\u043b\u0435\u043d\u0438\u0435: \u043f\u0440\u043e\u0435\u043a\u0442 \u0441\u0442\u0430\u043b \u043c\u0435\u043d\u044c\u0448\u0435\u2026",
            "is_opinion": False,
            "language": "ru",
            "link": "https://naked-science.ru/community/849188",
            "media": "https://naked-science.ru/wp-content/uploads/2023/05/image-74.png",
            "published_date": "2023-05-17 08:15:12",
            "published_date_precision": "full",
            "rank": 34919,
            "rights": "naked-science.ru",
            "summary": "\u042d\u0442\u043e\u0442 \u043f\u043e\u0441\u0442 \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d \u0447\u0438\u0442\u0430\u0442\u0435\u043b\u0435\u043c Naked Science \u0432 \u0440\u0430\u0437\u0434\u0435\u043b \n\u00ab\u0421\u043e\u043e\u0431\u0449\u0435\u0441\u0442\u0432\u043e\u00bb\n. \u0423\u0437\u043d\u0430\u0439\u0442\u0435 \u043a\u0430\u043a \u044d\u0442\u043e \u0441\u0434\u0435\u043b\u0430\u0442\u044c \u043f\u043e \n\u0441\u0441\u044b\u043b\u043a\u0435.\n \n\n\n\n\n \n \n \n\n\n\u041a\u043e\u043c\u043f\u0430\u043d\u0438\u044f Tesla \u043f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u0438\u043b\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u043d\u0443\u044e \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044e \u043e \u0441\u0432\u043e\u0435\u0439 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0435 \u0440\u043e\u0431\u043e\u0442\u043e\u0432-\u0433\u0443\u043c\u0430\u043d\u043e\u0438\u0434\u043e\u0432, \u0438\u0437\u0432\u0435\u0441\u0442\u043d\u043e\u0439 \u043a\u0430\u043a Tesla Bot \u0438\u043b\u0438 Optimus. \u041d\u043e\u0432\u044b\u0435 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f \u043f\u0440\u043e\u0442\u043e\u0442\u0438\u043f\u043e\u0432 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u044f\u0442 \u0432\u043f\u0435\u0447\u0430\u0442\u043b\u0435\u043d\u0438\u0435: \u043f\u0440\u043e\u0435\u043a\u0442 \u0441\u0442\u0430\u043b \u043c\u0435\u043d\u044c\u0448\u0435 \u043f\u043e\u0445\u043e\u0434\u0438\u0442\u044c \u043d\u0430 \u0434\u0438\u0437\u0430\u0439\u043d\u0435\u0440\u0441\u043a\u0438\u0435 \u0444\u0430\u043d\u0442\u0430\u0437\u0438\u0438, \u0438 \u0431\u043e\u043b\u044c\u0448\u0435 \u2014 \u043d\u0430 \u043f\u043e\u0442\u0435\u043d\u0446\u0438\u0430\u043b\u044c\u043d\u043e \u0440\u0435\u0430\u043b\u044c\u043d\u044b\u0439 \u043f\u0440\u043e\u0434\u0443\u043a\u0442.\n\n\n\n\n\n\n\n\n\n\n\u0421\u043e\u043e\u0431\u0449\u0435\u0441\u0442\u0432\u043e\n\n\n\n\n\n\n# Tesla\n\n\n\n\n\n\n# \u0420\u043e\u0431\u043e\u0442\u044b\n\n\n\n\n\n\n# \u0442\u0435\u0445\u043d\u043e\u043b\u043e\u0433\u0438\u0438\n\n\n\n\n \n\n\n\n\n\u00a9Tesla\n\u041d\u0430 \u0441\u043e\u0431\u0440\u0430\u043d\u0438\u0438 \u0430\u043a\u0446\u0438\u043e\u043d\u0435\u0440\u043e\u0432 Tesla \u041c\u0430\u0441\u043a \u043f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u0438\u043b \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u043d\u0443\u044e \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044e \u043e Tesla Bot, \u043a\u043e\u0442\u043e\u0440\u0430\u044f \u0432\u043a\u043b\u044e\u0447\u0430\u043b\u0430 \u0432\u0438\u0434\u0435\u043e \u0438 \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f \u043d\u0435\u0441\u043a\u043e\u043b\u044c\u043a\u0438\u0445 \u043f\u0440\u043e\u0442\u043e\u0442\u0438\u043f\u043e\u0432 \u0440\u043e\u0431\u043e\u0442\u043e\u0432.",
            "title": "Tesla Bot \u044d\u0432\u043e\u043b\u044e\u0446\u0438\u043e\u043d\u0438\u0440\u0443\u0435\u0442: \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u044f \u0418\u043b\u043e\u043d\u0430 \u041c\u0430\u0441\u043a\u0430 \u043f\u043e\u043a\u0430\u0437\u0430\u043b\u0430 \u043d\u043e\u0432\u044b\u0435 \u043f\u0440\u043e\u0442\u043e\u0442\u0438\u043f\u044b \u0440\u043e\u0431\u043e\u0442\u043e\u0432",
            "topic": "tech",
            "twitter_account": "@nakedsci",
        },
        {
            "_id": "f2ad383e66898226ba7ab70ff9e0c4a8",
            "_score": 12.744526,
            "author": "Randall Chase",
            "authors": "AP Business Writer,RANDALL CHASE",
            "clean_url": "seattlepi.com",
            "country": "US",
            "excerpt": "DOVER, Del. (AP) \u2014",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.seattlepi.com/business/article/state-supreme-court-overturns-judge-s-ruling-18100960.php",
            "media": "https://www.seattlepi.com/img/modules/siteheader/brand.png",
            "published_date": "2023-05-15 22:25:25",
            "published_date_precision": "full",
            "rank": 2280,
            "rights": "seattlepi.com",
            "summary": "FILE - A Tesla Supercharger is seen at Willow Festival shopping plaza parking lot, Aug. 10, 2022, in Northbrook, Ill. On Monday, May 15, 2023, Delaware's Supreme Court overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers.\nNam Y. Huh/AP\nAdvertisement\nArticle continues below this ad\nDelaware's Supreme Court on Monday overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers.",
            "title": "State Supreme Court overturns judge's ruling prohibiting Tesla dealership in Delaware",
            "topic": "business",
            "twitter_account": "@SeattlePI",
        },
        {
            "_id": "4270c2a93c70c4dea33921d35414867a",
            "_score": 12.739283,
            "author": "Griffin Davis",
            "authors": "Griffin Davis",
            "clean_url": "techtimes.com",
            "country": "US",
            "excerpt": "The billionaire claims that the demand for Optimus could reach billions of units.",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.techtimes.com/articles/291694/20230518/elon-musks-optimus-prediction-demand-tesla-bot-reach-20-billion.htm",
            "media": "https://1734811051.rsc.cdn77.org/data/images/full/427966/elon-musks-optimus-prediction-demand-for-tesla-bot-could-reach-20-billion-units.jpg",
            "published_date": "2023-05-18 20:07:47",
            "published_date_precision": "full",
            "rank": 2599,
            "rights": "techtimes.com",
            "summary": "Griffin Davis \n, Tech Times \n18 May 2023, 04:05 pm\n \n \nElon Musk makes a bold prediction for his Optimus (aka Tesla Bot).\n \n \n(Photo: Maja Hitij/Getty Images)\n Tesla head Elon Musk arrives to look at the new Tesla Gigafactory construction site near Berlin on September 03, 2020, near Gruenheide, Germany.\n \n \nHe claims that the demand for the humanoid robot could reach over 10,000 billion units. The billionaire shared his remarks at the recent Tesla shareholder meeting. Musk's bold predictions are commonly about his Tesla EV technologies.",
            "title": "Elon Musk's Optimus Prediction: Demand for Tesla Bot Could Reach 20 Billion Units!",
            "topic": "news",
            "twitter_account": "@TechTimes_News",
        },
        {
            "_id": "94c05834afd24a947dfbdab98be164a0",
            "_score": 12.736555,
            "author": "CNA",
            "authors": "CNA",
            "clean_url": "channelnewsasia.com",
            "country": "SG",
            "excerpt": "San Francisco : Tesla is offering discounts of more than $1,300 on some Model 3 cars in its U.S. inventory following even heavier discounts in Europe, according to a Reuters' review of its website,\u2026",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.channelnewsasia.com/business/tesla-offering-discounts-over-1300-some-us-model-3-cars-website-3502051",
            "media": "https://onecms-res.cloudinary.com/image/upload/s--sqYQzWCN--/fl_relative,g_south_east,l_one-cms:core:watermark:reuters,w_0.1/f_auto,q_auto/c_fill,g_auto,h_676,w_1200/v1/one-cms/core/2023-05-19t203815z_4_lynxmpej4i0t1_rtroptp_3_health-coronavirus-tesla-california.jpg?itok=ggqsjdqF",
            "published_date": "2023-05-19 18:52:33",
            "published_date_precision": "full",
            "rank": 1591,
            "rights": "channelnewsasia.com",
            "summary": "San Francisco : Tesla is offering discounts of more than $1,300 on some Model 3 cars in its U.S. inventory following even heavier discounts in Europe, according to a Reuters' review of its website, even as the electric carmaker has raised U.S. prices on most newly ordered cars this month.\nFacing economic headwinds and mounting competition, Tesla this year has aggressively cut vehicle prices in several regions and is resorting to the traditional automakers' tactic of offering incentives to clear inventory, analysts said.",
            "title": "Tesla offering discounts of over $1,300 on some US Model 3 cars-website",
            "topic": "business",
            "twitter_account": "@ChannelNewsAsia",
        },
        {
            "_id": "586aac52a37b509f5156347e4f1fa9eb",
            "_score": 12.735738,
            "author": "Associated Press",
            "authors": "Associated Press",
            "clean_url": "usnews.com",
            "country": "US",
            "excerpt": "Delaware's Supreme Court has overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.usnews.com/news/business/articles/2023-05-15/state-supreme-court-overturns-judges-ruling-prohibiting-tesla-dealership-in-delaware",
            "media": "https://www.usnews.com/dims4/USNEWS/aba6e24/2147483647/thumbnail/970x647/quality/85/?url=https%3A%2F%2Fwww.usnews.com%2Fcmsmedia%2Fb2%2Fe9d604c2e2a2c78e61fd24ff852ff2%2F825372bfe77843e49a5d2d321b1ea598Tesla_Delaware_83849.jpg",
            "published_date": "2023-05-15 22:25:00",
            "published_date_precision": "full",
            "rank": 248,
            "rights": None,
            "summary": "DOVER, Del. (AP) \u2014\n\nDelaware's Supreme Court on Monday overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers.\n\nIn a ruling last year, a Superior Court judge determined that Delaware's Motor Vehicle Franchising Practices Act prohibited Tesla, as a manufacturer, from selling its electric cars directly to customers in Delaware.\n\nThe Supreme Court reversed that decision and sent the case back to Superior Court, noting that the franchise act was enacted to address the disparity in bargaining power that permitted automobile manufacturers to exert economic pressure over their franchises.",
            "title": "State Supreme Court Overturns Judge's Ruling Prohibiting Tesla Dealership in Delaware",
            "topic": "news",
            "twitter_account": None,
        },
        {
            "_id": "b8525aade36be44970d4e6081a883a76",
            "_score": 12.731351,
            "author": "RANDALL CHASE",
            "authors": "RANDALL CHASE",
            "clean_url": "apnews.com",
            "country": "US",
            "excerpt": "Delaware's Supreme Court has overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers. A Superior Court judge ruled last year that Delaware's Motor Vehicle Franchising Practices Act prohibits Tesla, as a manufacturer, from selling its electric cars directly to customers in Delaware. The Supreme Court reversed that decision on Monday and sent the case back to Superior Court. The justices noted that the franchise act was enacted to address the disparity in bargaining power that permitted automobile manufacturers to exert economic pressure over their franchises. Tesla sells its vehicles directly to consumers without using independent franchise dealers.",
            "is_opinion": False,
            "language": "en",
            "link": "https://apnews.com/article/tesla-automobile-industry-electric-vehicles-car-dealers-ef22d03da07b4c291d8ce76ba9a3cfef",
            "media": "https://storage.googleapis.com/afs-prod/media/825372bfe77843e49a5d2d321b1ea598/3000.webp",
            "published_date": "2023-05-15 22:25:38",
            "published_date_precision": "full",
            "rank": 353,
            "rights": "apnews.com",
            "summary": "DOVER, Del. (AP) \u2014\n\nDelaware's Supreme Court on Monday overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers.\n\nIn a ruling last year, a Superior Court judge determined that Delaware's Motor Vehicle Franchising Practices Act prohibited Tesla, as a manufacturer, from selling its electric cars directly to customers in Delaware.\n\nThe Supreme Court reversed that decision and sent the case back to Superior Court, noting that the franchise act was enacted to address the disparity in bargaining power that permitted automobile manufacturers to exert economic pressure over their franchises.",
            "title": "State Supreme Court overturns judge's ruling prohibiting Tesla dealership in Delaware",
            "topic": "news",
            "twitter_account": "@ap",
        },
        {
            "_id": "c6b09e48c7ce1a86cd7621628104de36",
            "_score": 12.730695,
            "author": "Cristian Agatie",
            "authors": "Cristian Agatie",
            "clean_url": "autoevolution.com",
            "country": "RO",
            "excerpt": "Tesla applied to expand Giga Shanghai and add a new production line for pouch-type batteries. The information is intriguing, as Tesla only uses cylindric...",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.autoevolution.com/news/tesla-plans-giga-shanghai-expansion-with-intriguing-pouch-type-cell-production-line-215079.html",
            "media": "https://s1.cdn.autoevolution.com/images/news/tesla-plans-giga-shanghai-expansion-with-intriguing-pouch-type-cell-production-line-215079_1.jpg",
            "published_date": "2023-05-16 13:13:54",
            "published_date_precision": "full",
            "rank": 5202,
            "rights": "autoevolution.com",
            "summary": "Tesla applied to expand Giga Shanghai and add a new production line for pouch-type batteries. The information is intriguing, as Tesla only uses cylindrical cells and has previously warned that pouch cells are too dangerous to be used in an electric vehicle.\n\n\n\n\n\n\n\n\n 6 photos\nPhoto: Tesla | Edited\n \n Despite rumors that Tesla is facing a \ndemand problem\n, the \nEV\n maker is expanding its production capacity throughout its factories. Although production has remained flat in the first quarter, this is usually the weakest, and Tesla expects the demand to increase in the coming months.",
            "title": "Tesla Plans Giga Shanghai Expansion With Intriguing Pouch-Type Cell Production Line",
            "topic": "news",
            "twitter_account": "@_autoevolution_",
        },
        {
            "_id": "223e3a7b3134606695700e45f28979c6",
            "_score": 12.730671,
            "author": "Randall Chase",
            "authors": "Randall Chase",
            "clean_url": "washingtonpost.com",
            "country": "US",
            "excerpt": "Delaware's Supreme Court has overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.washingtonpost.com/business/2023/05/15/tesla-automobile-industry-electric-vehicles-car-dealers/7659e2aa-f36f-11ed-918d-012572d64930_story.html",
            "media": "https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/OQXBX2XTN4I63EMNAESXFVSJGA_size-normalized.jpg&w=1440",
            "published_date": "2023-05-15 22:25:57",
            "published_date_precision": "full",
            "rank": 83,
            "rights": "washingtonpost.com",
            "summary": "Delaware's Supreme Court on Monday overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers.\nIn a ruling last year, a Superior Court judge determined that Delaware's Motor Vehicle Franchising Practices Act prohibited Tesla, as a manufacturer, from selling its electric cars directly to customers in Delaware.\nThe Supreme Court reversed that decision and sent the case back to Superior Court, noting that the franchise act was enacted to address the disparity in bargaining power that permitted automobile manufacturers to exert economic pressure over their franchises.",
            "title": "State Supreme Court overturns judge's ruling prohibiting Tesla dealership in Delaware",
            "topic": "news",
            "twitter_account": "@WashingtonPost",
        },
        {
            "_id": "1be9f349c1136dc5c7ed0ce9a4cbe658",
            "_score": 12.730011,
            "author": "RANDALL CHASE",
            "authors": "Associated Press,Fatima Hussein,Hours Ago,Josh Funk,Larry Neumeister,Lisa Mascaro,Mins Ago,RANDALL CHASE,Stan Choe",
            "clean_url": "thehill.com",
            "country": "US",
            "excerpt": "DOVER, Del. (AP) \u2014 Delaware's Supreme Court on Monday overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to \u2026",
            "is_opinion": False,
            "language": "en",
            "link": "https://thehill.com/homenews/ap/ap-business/state-supreme-court-overturns-judges-ruling-prohibiting-tesla-dealership-in-delaware/",
            "media": "https://thehill.com/wp-content/uploads/sites/2/2023/05/6462b2330a3a71.27623915.jpeg?w=1280",
            "published_date": "2023-05-15 22:25:25",
            "published_date_precision": "full",
            "rank": 570,
            "rights": "thehill.com",
            "summary": "DOVER, Del. (AP) \u2014\n\nDelaware's Supreme Court on Monday overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers.\n\nIn a ruling last year, a Superior Court judge determined that Delaware's Motor Vehicle Franchising Practices Act prohibited Tesla, as a manufacturer, from selling its electric cars directly to customers in Delaware.\n\nThe Supreme Court reversed that decision and sent the case back to Superior Court, noting that the franchise act was enacted to address the disparity in bargaining power that permitted automobile manufacturers to exert economic pressure over their franchises.",
            "title": "State Supreme Court overturns judge's ruling prohibiting Tesla dealership in Delaware",
            "topic": "news",
            "twitter_account": None,
        },
        {
            "_id": "abf335d97ef89589b2655d3c7358b6a5",
            "_score": 12.729826,
            "author": "RANDALL CHASE",
            "authors": "Associated Press,RANDALL CHASE",
            "clean_url": "daytondailynews.com",
            "country": "US",
            "excerpt": "DOVER, Del. (AP) \u2014",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.daytondailynews.com/nation-world/state-supreme-court-overturns-judges-ruling-prohibiting-tesla-dealership-in-delaware/COVXVY5CLZFCHLLZ5XMR4GNLHE/",
            "media": "https://www.journal-news.com/resizer/-yc-3fe-u_tNFZbJin8y3e1vTms=/1200x630/cloudfront-us-east-1.images.arcpublishing.com/coxohio/3Q3IVAPS7MNGAQCEBM77PXOLHU.jpg",
            "published_date": "2023-05-15 22:25:50",
            "published_date_precision": "full",
            "rank": 5121,
            "rights": "journal-news.com",
            "summary": "The court ruling noted that Tesla has fought similar battles in several other states.\nTesla filed an application with the Delaware DMV for a dealer license in 2019. The DMV subsequently permitted Tesla to open a new car gallery in a shopping mall. The gallery allows customers to view Tesla vehicles, but Tesla cannot sell its cars from an in-state store.\nTesla submitted a second application for a dealer license in 2020. The DMV's Chief of Compliance and Investigation denied it, noting that Delaware's Licensing Act for automobile dealers requires that an applicant comply with state law before an application can be granted.",
            "title": "State Supreme Court overturns judge's ruling prohibiting Tesla dealership in Delaware",
            "topic": "world",
            "twitter_account": "@dayton-daily-news",
        },
        {
            "_id": "3bd130a074fa0c2b3ad5369bd140c629",
            "_score": 12.729565,
            "author": "info@focus.ua",
            "authors": "focus.ua,info@focus.ua,\u0420\u0435\u0434\u0430\u043a\u0446\u0438\u044f \u0424\u041e\u041a\u0423\u0421",
            "clean_url": "focus.ua",
            "country": "UA",
            "excerpt": "Tesla Roadster \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u043f\u043e\u043a\u043e\u043b\u0435\u043d\u0438\u044f \u0441\u0442\u0430\u043d\u0435\u0442 \u043d\u0438\u0448\u0435\u0432\u044b\u043c \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u043e\u043c \u0430\u043c\u0435\u0440\u0438\u043a\u0430\u043d\u0441\u043a\u043e\u0433\u043e \u0431\u0440\u0435\u043d\u0434\u0430. \u0418\u043b\u043e\u043d \u041c\u0430\u0441\u043a \u0437\u0430\u044f\u0432\u0438\u043b, \u0447\u0442\u043e \u043f\u0440\u043e\u0435\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u043c\u043e\u0434\u0435\u043b\u0438 \u0443\u0436\u0435 \u043f\u0440\u0438\u0431\u043b\u0438\u0436\u0430\u0435\u0442\u0441\u044f \u043a \u0444\u0438\u043d\u0430\u043b\u044c\u043d\u043e\u0439 \u0441\u0442\u0430\u0434\u0438\u0438.",
            "is_opinion": False,
            "language": "ru",
            "link": "https://focus.ua/auto/566921-uzhe-ne-za-gorami-ilon-mask-raskryl-vozmozhnuyu-datu-vyhoda-elektrokara-tesla-roadster",
            "media": "https://focus.ua/static/storage/thumbs/1200x630/7/86/9b34c880-47dff0a5a75fa2ce25bd9394693c4867.jpg?v=7976_1",
            "published_date": "2023-05-17 11:59:47",
            "published_date_precision": "full",
            "rank": 24539,
            "rights": "\u00a9 2023 \u041e\u041e\u041e \u00ab\u0424\u041e\u041a\u0423\u0421 \u041c\u0415\u0414\u0418\u0410\u00bb",
            "summary": "Tesla Roadster \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u043f\u043e\u043a\u043e\u043b\u0435\u043d\u0438\u044f \u0441\u0442\u0430\u043d\u0435\u0442 \u043d\u0438\u0448\u0435\u0432\u044b\u043c \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u043e\u043c \u0430\u043c\u0435\u0440\u0438\u043a\u0430\u043d\u0441\u043a\u043e\u0433\u043e \u0431\u0440\u0435\u043d\u0434\u0430. \u0418\u043b\u043e\u043d \u041c\u0430\u0441\u043a \u0437\u0430\u044f\u0432\u0438\u043b, \u0447\u0442\u043e \u043f\u0440\u043e\u0435\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u043c\u043e\u0434\u0435\u043b\u0438 \u0443\u0436\u0435 \u043f\u0440\u0438\u0431\u043b\u0438\u0436\u0430\u0435\u0442\u0441\u044f \u043a \u0444\u0438\u043d\u0430\u043b\u044c\u043d\u043e\u0439 \u0441\u0442\u0430\u0434\u0438\u0438.\n \n \n\u0413\u043b\u0430\u0432\u0430 Tesla \u0418\u043b\u043e\u043d \u041c\u0430\u0441\u043a \u043d\u0430\u0437\u0432\u0430\u043b \u0432\u043e\u0437\u043c\u043e\u0436\u043d\u0443\u044e \u0434\u0430\u0442\u0443 \u0432\u044b\u0445\u043e\u0434\u0430 \u044d\u043b\u0435\u043a\u0442\u0440\u043e\u043a\u0430\u0440\u0430 Tesla Roadster \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u043f\u043e\u043a\u043e\u043b\u0435\u043d\u0438\u044f. \u041f\u043e \u0435\u0433\u043e \u0441\u043b\u043e\u0432\u0430\u043c, \u043f\u0440\u043e\u0435\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u043c\u043e\u0434\u0435\u043b\u0438 \u043c\u043e\u0436\u0435\u0442 \u0437\u0430\u0432\u0435\u0440\u0448\u0438\u0442\u044c\u0441\u044f \u0443\u0436\u0435 \u0432 \u044d\u0442\u043e\u043c \u0433\u043e\u0434\u0443. \u041e\u0431 \u044d\u0442\u043e\u043c \n\u0440\u0430\u0441\u0441\u043a\u0430\u0437\u0430\u043b\u0438\n \u043d\u0430 \u0441\u0430\u0439\u0442\u0435 InsideEVs.\nTesla \u0432 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0435 \u0432\u0440\u0435\u043c\u044f \u0430\u043a\u0442\u0438\u0432\u043d\u043e \u0434\u0435\u043b\u0438\u0442\u0441\u044f \u043f\u043e\u0434\u0440\u043e\u0431\u043d\u043e\u0441\u0442\u044f\u043c\u0438 \u043e\u0431 \n\u044d\u043a\u0441\u0442\u0440\u0430\u0432\u0430\u0433\u0430\u043d\u0442\u043d\u043e\u043c \u044d\u043b\u0435\u043a\u0442\u0440\u0438\u0447\u0435\u0441\u043a\u043e\u043c \u043f\u0438\u043a\u0430\u043f\u0435 Cybertruck\n. \u041d\u0430 \u043d\u043e\u0432\u043e\u043c \u0441\u043e\u0431\u0440\u0430\u043d\u0438\u0438 \u0438\u043d\u0432\u0435\u0441\u0442\u043e\u0440\u043e\u0432 \u041c\u0430\u0441\u043a \u0443\u043f\u043e\u043c\u044f\u043d\u0443\u043b \u0438 Tesla Roadster \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u043f\u043e\u043a\u043e\u043b\u0435\u043d\u0438\u044f.",
            "title": "\u0423\u0436\u0435 \u043d\u0435 \u0437\u0430 \u0433\u043e\u0440\u0430\u043c\u0438: \u0418\u043b\u043e\u043d \u041c\u0430\u0441\u043a \u0440\u0430\u0441\u043a\u0440\u044b\u043b \u0432\u043e\u0437\u043c\u043e\u0436\u043d\u0443\u044e \u0434\u0430\u0442\u0443 \u0432\u044b\u0445\u043e\u0434\u0430 \u044d\u043b\u0435\u043a\u0442\u0440\u043e\u043a\u0430\u0440\u0430 Tesla Roadster",
            "topic": "news",
            "twitter_account": "@focusua",
        },
        {
            "_id": "23ed52b4e558ea1a4e76c64b493d1037",
            "_score": 12.727293,
            "author": "RANDALL CHASE",
            "authors": "AP Business Writer,Ariana Garcia,David Wethe,Faiz Siddiqui,Jeremy B. Merrill,Kevin Crowley,RANDALL CHASE,Rachel Butt,Rachel Lerman",
            "clean_url": "chron.com",
            "country": "US",
            "excerpt": "DOVER, Del. (AP) \u2014",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.chron.com/business/article/state-supreme-court-overturns-judge-s-ruling-18100960.php",
            "media": "https://s.hdnux.com/photos/01/32/71/25/23827788/3/rawImage.jpg",
            "published_date": "2023-05-15 22:25:25",
            "published_date_precision": "full",
            "rank": 582,
            "rights": "chron.com",
            "summary": "DOVER, Del. (AP) \u2014\n\nDelaware's Supreme Court on Monday overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers.\n\nIn a ruling last year, a Superior Court judge determined that Delaware's Motor Vehicle Franchising Practices Act prohibited Tesla, as a manufacturer, from selling its electric cars directly to customers in Delaware.\n\nThe Supreme Court reversed that decision and sent the case back to Superior Court, noting that the franchise act was enacted to address the disparity in bargaining power that permitted automobile manufacturers to exert economic pressure over their franchises.",
            "title": "State Supreme Court overturns judge's ruling prohibiting Tesla dealership in Delaware",
            "topic": "business",
            "twitter_account": "@chron",
        },
        {
            "_id": "8be056c5e741bd052af0f0442d020ca5",
            "_score": 12.726501,
            "author": "HT Auto Desk",
            "authors": "HT Auto Desk",
            "clean_url": "hindustantimes.com",
            "country": "IN",
            "excerpt": "Tesla is reportedly eyeing an EV plant in India. But where are its biggest manufacturing hubs at present?",
            "is_opinion": False,
            "language": "en",
            "link": "https://auto.hindustantimes.com/web-stories/is-tesla-finally-coming-to-india-top-five-factory-sites-in-the-world-41684384006562",
            "media": "https://images.hindustantimes.com/auto/img/2023/05/18/1600x900/Tesla__1684384961634_1684384969763.jpg",
            "published_date": "2023-05-17 22:56:46",
            "published_date_precision": "full",
            "rank": 980,
            "rights": "hindustantimes.com",
            "summary": "Tesla is reportedly eyeing an EV plant in India. But where are its biggest manufacturing hubs at present?\n \n \n \n \n \n \n \n \n \n \n \n \n \n California: Tesla factory in Fremont is one its oldest with annual capacity of 650,000 units per year\n \n \n \n \n \n \n \n \n \n \n \n \n \n Shanghai: Tesla China plant was its first outside of the US. It has a capacity of 750,000 units\n \n \n \n \n \n \n \n \n \n \n \n \n \n Berlin: Tesla plant in Germany manufactures Model Y and has an estimated annual capacity of 250,000 units\n \n \n \n \n \n \n \n \n \n \n \n \n \n Texas: Tesla has moved its HQ to just outside of Houston.",
            "title": "Is Tesla finally coming to India? Top-five factory sites in the world",
            "topic": "news",
            "twitter_account": "@HTAutotweets",
        },
        {
            "_id": "c95a914d541d0524bdd6bf64051ad2c0",
            "_score": 12.725132,
            "author": "RANDALL CHASE",
            "authors": "AP Business Writer,RANDALL CHASE",
            "clean_url": "sfgate.com",
            "country": "US",
            "excerpt": "DOVER, Del. (AP) \u2014",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.sfgate.com/business/article/state-supreme-court-overturns-judge-s-ruling-18100960.php",
            "media": "https://s.hdnux.com/photos/01/32/71/25/23827788/3/rawImage.jpg",
            "published_date": "2023-05-15 22:25:25",
            "published_date_precision": "full",
            "rank": 410,
            "rights": "sfgate.com",
            "summary": "In a ruling last year, a Superior Court judge determined that Delaware's Motor Vehicle Franchising Practices Act prohibited Tesla, as a manufacturer, from selling its electric cars directly to customers in Delaware.\n\nThe Supreme Court reversed that decision and sent the case back to Superior Court, noting that the franchise act was enacted to address the disparity in bargaining power that permitted automobile manufacturers to exert economic pressure over their franchises. The justices said the law's definitions exclude Tesla because the company sells its vehicles directly to consumers without using independent franchise dealers.",
            "title": "State Supreme Court overturns judge's ruling prohibiting Tesla dealership in Delaware",
            "topic": "business",
            "twitter_account": "@SFGate",
        },
        {
            "_id": "28f4760f1726cdfe2d5fa11bed9c6d7c",
            "_score": 12.724205,
            "author": "RANDALL CHASE",
            "authors": "Associated Press,RANDALL CHASE",
            "clean_url": "wfla.com",
            "country": "US",
            "excerpt": "DOVER, Del. (AP) \u2014 Delaware's Supreme Court on Monday overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to \u2026",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.wfla.com/business/ap-business/state-supreme-court-overturns-judges-ruling-prohibiting-tesla-dealership-in-delaware/",
            "media": "https://www.wfla.com/wp-content/uploads/sites/71/2023/05/6462b22ce5b0c0.53934285.jpeg?w=1280",
            "published_date": "2023-05-15 22:25:25",
            "published_date_precision": "full",
            "rank": 4949,
            "rights": "wfla.com",
            "summary": "DOVER, Del. (AP) \u2014\n\nDelaware's Supreme Court on Monday overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers.\n\nIn a ruling last year, a Superior Court judge determined that Delaware's Motor Vehicle Franchising Practices Act prohibited Tesla, as a manufacturer, from selling its electric cars directly to customers in Delaware.\n\nThe Supreme Court reversed that decision and sent the case back to Superior Court, noting that the franchise act was enacted to address the disparity in bargaining power that permitted automobile manufacturers to exert economic pressure over their franchises.",
            "title": "State Supreme Court overturns judge's ruling prohibiting Tesla dealership in Delaware",
            "topic": "business",
            "twitter_account": None,
        },
        {
            "_id": "ed570007d52e04efe2fb1679607be9bd",
            "_score": 12.717861,
            "author": "Michael Elkins",
            "authors": "Investing.com,Michael Elkins",
            "clean_url": "investing.com",
            "country": "ES",
            "excerpt": "Tesla reopens talks with India, proposes new EV factory",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.investing.com/news/stock-market-news/tesla-reopens-talks-with-india-proposes-new-ev-factory-432SI-3084842",
            "media": "https://i-invdn-com.investing.com/news/Tesla_800x533_L_1522586972.jpg",
            "published_date": "2023-05-17 14:47:00",
            "published_date_precision": "full",
            "rank": 1372,
            "rights": "investing.com",
            "summary": "Reuters reports, citing a source with direct knowledge of the matter, that electric vehicle giant Tesla (NASDAQ: TSLA) told government officials on Wednesday they would like to build a factory in India to build electric cars for domestic sale and export.\n\nThe proposal comes after India refused to agree to Tesla's request last year to lower the import tax on cars, which can reach as much as 100%. India insisted that Tesla manufacture vehicles locally but Tesla wanted to test the market first with imports.",
            "title": "Tesla reopens talks with India, proposes new EV factory",
            "topic": "finance",
            "twitter_account": None,
        },
        {
            "_id": "a1fbf2df588e22e95a8e002eb1ffce80",
            "_score": 12.717767,
            "author": "RANDALL CHASE",
            "authors": "RANDALL CHASE",
            "clean_url": "seattletimes.com",
            "country": "US",
            "excerpt": "Delaware's Supreme Court has overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers.",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.seattletimes.com/business/state-supreme-court-overturns-judges-ruling-prohibiting-tesla-dealership-in-delaware/?utm_source=RSS&utm_medium=Referral&utm_campaign=RSS_all",
            "media": "https://images.seattletimes.com/wp-content/uploads/2023/05/urnpublicidap.orgef22d03da07b4c291d8ce76ba9a3cfefTesla_Delaware_83849.jpg?d=1200x630",
            "published_date": "2023-05-15 22:26:04",
            "published_date_precision": "full",
            "rank": 810,
            "rights": None,
            "summary": "DOVER, Del. (AP) \u2014\n\nDelaware's Supreme Court on Monday overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers.\n\nIn a ruling last year, a Superior Court judge determined that Delaware's Motor Vehicle Franchising Practices Act prohibited Tesla, as a manufacturer, from selling its electric cars directly to customers in Delaware.\n\nThe Supreme Court reversed that decision and sent the case back to Superior Court, noting that the franchise act was enacted to address the disparity in bargaining power that permitted automobile manufacturers to exert economic pressure over their franchises.",
            "title": "State Supreme Court overturns judge's ruling prohibiting Tesla dealership in Delaware",
            "topic": "news",
            "twitter_account": None,
        },
        {
            "_id": "29c6026cf780dc3bde5738477dd7db01",
            "_score": 12.715607,
            "author": "Insider",
            "authors": "Insider,You Might Also Like",
            "clean_url": "msn.com",
            "country": "US",
            "excerpt": "Nearly every vehicle Tesla has ever sold in China is being recalled for a potentially dangerous braking and accelerating defect. A total of 1.1 million Tesla Model S,",
            "is_opinion": False,
            "language": "en",
            "link": "http://www.msn.com/en-us/autos/news/tesla-is-recalling-millions-of-cars-in-china/ar-AA1baOYm",
            "media": "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1baUjJ.img?h=315&w=600&m=6&q=60&o=t&l=f&f=jpg",
            "published_date": "2023-05-14 16:15:00",
            "published_date_precision": "timezone unknown",
            "rank": 100,
            "rights": "msn.com",
            "summary": "Nearly every vehicle Tesla has ever sold in China is being recalled for a potentially dangerous braking and accelerating defect.\nA total of 1.1 million Tesla Model S, Model X, Model 3 and Model Y vehicles are included in the recall, Chinese regulators said Friday. Tesla has sold about 1.13 million cars since it arrived in China in 2014.\nTesla plans to fix the issue with an over-the-air software update, which will allow drivers to have more control over the intensity of their regenerative braking system, which is at the core of the recall.",
            "title": "Tesla is recalling millions of cars in China",
            "topic": "news",
            "twitter_account": None,
        },
        {
            "_id": "518ba884625797327a2659d7b6a9407c",
            "_score": 12.711708,
            "author": "Wawan Priyanto",
            "authors": "Dicky Kurniawan,Wawan Priyanto",
            "clean_url": "tempo.co",
            "country": "ID",
            "excerpt": "Sejumlah pemilik Tesla Model S dan Model X di AS mengajukan gugatan terhadap Tesla atas pembaruan perangkat lunak otomatis yang dihadirkan.",
            "is_opinion": False,
            "language": "id",
            "link": "https://otomotif.tempo.co/read/1725507/update-software-tesla-berbuntut-gugatan-dari-konsumen-apa-masalahnya",
            "media": "https://statik.tempo.co/data/2020/12/24/id_989775/989775_720.jpg",
            "published_date": "2023-05-14 04:00:00",
            "published_date_precision": "full",
            "rank": 9966,
            "rights": "tempo.co",
            "summary": "TEMPO.CO\n, \nJakarta\n -\u00a0\nTesla\n menggulirkan pembaruan perangkat lunak (software) untuk mobil listriknya. Alih-alih memberikan pelayanan untuk konsumennya, namun siapa sangka para pemilik mobil Tesla di Amerika Serikat justru menggugat Tesla akibat update software tersebut.\nMelansir laman \nAutoblog\n hari ini, Minggu, 14 Mei 2023, sejumlah pemilik Tesla \nModel S\n dan Model X di AS mengajukan gugatan terhadap Tesla atas pembaruan perangkat lunak otomatis yang dihadirkan. Konsumen menilai update software tersebut justru menurunkan daya jangkau kendaraan dan bisa merusak baterai.",
            "title": "Update Software Tesla Berbuntut Gugatan dari Konsumen, Apa Masalahnya?",
            "topic": "news",
            "twitter_account": None,
        },
        {
            "_id": "9f55dd0287f49d4958ba225511ea9f35",
            "_score": 12.710878,
            "author": "Silvian Irimia",
            "authors": "Silvian Irimia",
            "clean_url": "autoevolution.com",
            "country": "RO",
            "excerpt": "Elon Musk's innovative electric car brand single-handedly transformed the automotive landscape, igniting a revolution that began with the groundbrea...",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.autoevolution.com/news/tesla-s-game-changing-impact-on-the-automotive-landscape-215327.html",
            "media": "https://s1.cdn.autoevolution.com/images/news/tesla-s-game-changing-impact-on-the-automotive-landscape-215327_1.jpg",
            "published_date": "2023-05-20 20:29:13",
            "published_date_precision": "full",
            "rank": 5202,
            "rights": "2008-2023 autoevolution. All rights reserved.",
            "summary": "While some may argue that \nTesla\n simply rode the tide of \nEV\n success, the truth is they took a leap of faith, ushering in the era of electric vehicles long before it became a widespread phenomenon. Tesla captured the world's attention with its impressive straight-line performance, captivating in-car innovations, and groundbreaking autonomous driving capabilities. They succeeded in making EVs excellent and establishing them as a viable and compelling alternative to traditional internal combustion engines.",
            "title": "Tesla's Game-Changing Impact on the Automotive Landscape",
            "topic": "news",
            "twitter_account": "@_autoevolution_",
        },
        {
            "_id": "3edccff4c17f3b601982995656efcf74",
            "_score": 12.709909,
            "author": "RANDALL CHASE",
            "authors": "Ap Business Writer,Christian Leonard,Nanette Asimov,Nora Mishanec,Omar Mamoon,RANDALL CHASE,Rachel Swan",
            "clean_url": "sfchronicle.com",
            "country": "US",
            "excerpt": "DOVER, Del. (AP) \u2014",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.sfchronicle.com/business/article/state-supreme-court-overturns-judge-s-ruling-18100960.php",
            "media": "https://s.hdnux.com/photos/01/32/71/25/23827788/3/rawImage.jpg",
            "published_date": "2023-05-15 22:25:25",
            "published_date_precision": "full",
            "rank": 1425,
            "rights": "sfchronicle.com",
            "summary": "In a ruling last year, a Superior Court judge determined that Delaware's Motor Vehicle Franchising Practices Act prohibited Tesla, as a manufacturer, from selling its electric cars directly to customers in Delaware.\n\nThe Supreme Court reversed that decision and sent the case back to Superior Court, noting that the franchise act was enacted to address the disparity in bargaining power that permitted automobile manufacturers to exert economic pressure over their franchises. The justices said the law's definitions exclude Tesla because the company sells its vehicles directly to consumers without using independent franchise dealers.",
            "title": "State Supreme Court overturns judge's ruling prohibiting Tesla dealership in Delaware",
            "topic": "business",
            "twitter_account": "@sfchronicle",
        },
        {
            "_id": "d705c2a589353e768a87d7d01f0b0054",
            "_score": 12.709567,
            "author": "RANDALL CHASE",
            "authors": "RANDALL CHASE",
            "clean_url": "wftv.com",
            "country": "US",
            "excerpt": "Delaware's Supreme Court has overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.wftv.com/news/state-supreme-court/BSVYOZNV2CPXUO5OILODXNZK7U/",
            "media": "https://cmg-cmg-tv-10070-prod.cdn.arcpublishing.com/resizer/5OrJRKClcXjPrFSFx4DLwiFUCbc=/1440x810/filters:format(jpg):quality(70)/cloudfront-us-east-1.images.arcpublishing.com/cmg/EUZMZZYNUANZFZVNFC3TWR23GE.jpg",
            "published_date": "2023-05-15 22:30:11",
            "published_date_precision": "full",
            "rank": 5925,
            "rights": "wftv.com",
            "summary": "DOVER, Del. \u2014 (AP) \u2014\n\nDelaware's Supreme Court on Monday overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers.\n\nIn a ruling last year, a Superior Court judge determined that Delaware's Motor Vehicle Franchising Practices Act prohibited Tesla, as a manufacturer, from selling its electric cars directly to customers in Delaware.\n\nThe Supreme Court reversed that decision and sent the case back to Superior Court, noting that the franchise act was enacted to address the disparity in bargaining power that permitted automobile manufacturers to exert economic pressure over their franchises.",
            "title": "State Supreme Court overturns judge's ruling prohibiting Tesla dealership in Delaware",
            "topic": "news",
            "twitter_account": "@wftv",
        },
        {
            "_id": "a026f3d7ed1d119618aad6c878b0fc85",
            "_score": 12.70866,
            "author": "Finanzen.Net Redaktion",
            "authors": "Finanzen.Net Redaktion",
            "clean_url": "finanzen.net",
            "country": "DE",
            "excerpt": "Zu den Verlierern des Tages z\u00e4hlt am Donnerstagnachmittag die Aktie von Tesla. Die Aktie verlor zuletzt in der NASDAQ Bsc-Sitzung 0,4 Prozent auf 173,10 USD. 18.05.2023",
            "is_opinion": False,
            "language": "de",
            "link": "https://www.finanzen.net/nachricht/aktien/tesla-aktie-kursbewegung-18-05-2023-11202033",
            "media": "https://images.finanzen.net/images/logos/finanzennet_660x303.png",
            "published_date": "2023-05-18 16:08:00",
            "published_date_precision": "timezone unknown",
            "rank": 6849,
            "rights": "finanzen.net",
            "summary": "Die Tesla-Aktie wies um 16:08 Uhr Verluste aus. Im NASDAQ Bsc-Handel ging es f\u00fcr das Papier um 0,4 Prozent auf 173,10 USD abw\u00e4rts. Die gr\u00f6\u00dften Abgaben verzeichnete die Tesla-Aktie bis auf 172,45 USD. Zum NASDAQ Bsc-Handelsstart notierte das Papier bei 174,28 USD. Zuletzt stieg das NASDAQ Bsc-Volumen auf 24.238.003 Tesla-Aktien.\nMit einem Kursgewinn bis auf 314,67 USD erreichte der Titel am 17.08.2022 ein 52-Wochen-Hoch. Der aktuelle Kurs der Tesla-Aktie ist somit 81,78 Prozent vom 52-Wochen-Hoch entfernt.",
            "title": "Tesla Aktie News: S&P 500 Aktie Anleger schicken Tesla am Nachmittag ins Minus",
            "topic": "news",
            "twitter_account": None,
        },
        {
            "_id": "fa65aad522e8a367c07dcfd46dbf6893",
            "_score": 12.7081,
            "author": "Aliki Kraterou",
            "authors": "Aliki Kraterou,Laura Donaldson,Sarah Grealish",
            "clean_url": "thesun.ie",
            "country": "IE",
            "excerpt": "TESLA is the world-renowned electric vehicle manufacturer, co-founded by Elon Musk, that has gained huge popularity since its inception in 2003. The luxury eco-cars are lauded for being a part of t\u2026",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.thesun.ie/news/7250853/tesla-cost-how-much/",
            "media": "https://www.thesun.ie/wp-content/uploads/sites/3/2021/08/RTRMADP_TESLA-PRODUCTION-FORECAST_1053866326_RC2ORW93Y0Z4_2022-09-30T135045Zjpg-JS764673495.jpg?strip=all&quality=100&w=1920&h=1080&crop=1",
            "published_date": "2023-05-18 14:42:28",
            "published_date_precision": "full",
            "rank": 6724,
            "rights": "thesun.ie",
            "summary": "TESLA is the world-renowned electric vehicle manufacturer, co-founded by Elon Musk, that has gained huge popularity since its inception in 2003. \n\n\nThe \nluxury eco-cars\n are lauded for being a part of the clean energy revolution and are the best-selling electric vehicles in the UK, but they do come at a pretty hefty price.\n\n\nTesla Motors is co-founded by Elon Musk, pictured at the Tesla factory in Fremont, California\n\n\nHow much does a Tesla cost?\n\n\nTesla\n offers four car models: the Model S, Model 3, Model X and Model Y.",
            "title": "How much does a Tesla cost in the UK?",
            "topic": "news",
            "twitter_account": "@IrishSunOnline",
        },
        {
            "_id": "5b607c9568e1ccee26c9e4e35c83a5bb",
            "_score": 12.706551,
            "author": "The Associated Press",
            "authors": "The Associated Press",
            "clean_url": "newsday.com",
            "country": "US",
            "excerpt": "Delaware's Supreme Court has overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers",
            "is_opinion": False,
            "language": "en",
            "link": "https://www.newsday.com/business/state-supreme-court-overturns-judges-ruling-prohibiting-tesla-dealership-in-delaware-qlzr4hgc",
            "media": "https://cdn.newsday.com/ace/c:MzExZTY0MTQtMTk4Yi00:NDQ4ODBk/landscape/1280",
            "published_date": "2023-05-15 22:26:05",
            "published_date_precision": "full",
            "rank": 1458,
            "rights": "newsday.com",
            "summary": "DOVER, Del. \u2014\n\nDelaware's Supreme Court on Monday overturned a judge's ruling upholding a decision by state officials to prohibit electric vehicle maker Tesla from selling its cars directly to customers.\n\nIn a ruling last year, a Superior Court judge determined that Delaware's Motor Vehicle Franchising Practices Act prohibited Tesla, as a manufacturer, from selling its electric cars directly to customers in Delaware.\n\nThe Supreme Court reversed that decision and sent the case back to Superior Court, noting that the franchise act was enacted to address the disparity in bargaining power that permitted automobile manufacturers to exert economic pressure over their franchises.",
            "title": "State Supreme Court overturns judge's ruling prohibiting Tesla dealership in Delaware",
            "topic": "news",
            "twitter_account": "@newsday",
        },
    ],
    "page": 1,
    "page_size": 50,
    "status": "ok",
    "total_hits": 10000,
    "total_pages": 200,
    "user_input": {
        "countries": None,
        "from": "2023-05-14 00:00:00",
        "from_rank": None,
        "lang": None,
        "not_countries": None,
        "not_lang": None,
        "not_sources": [],
        "page": 1,
        "published_date_precision": None,
        "q": "Tesla",
        "ranked_only": "True",
        "search_in": ["title_summary"],
        "size": 50,
        "sort_by": "relevancy",
        "sources": None,
        "to": None,
        "to_rank": None,
        "topic": None,
    },
}
